
spring:
  application:
    name: bene
  jpa:
    generate-ddl: true
    show-sql: true
  cloud:
    config:
      uri: http://configshost.cfapps.io

management:
  security:
    enabled: false

server:
  port: 8084

producer:
  ribbon:
    ServerListRefreshInterval: 5000

---
spring:
  profiles: dev

security:
  basic:
    enabled: false
